{
 "title": "PHP-FPM - Simple pool",
 "description": "PHP-FPM detailed page for single FPM pool.",
 "tags": [ "php-fpm" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "label_values(php_fpm_accepted_connections_total, instance)"
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "Interval", "label": "Time Interval", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "Socket",
    "label": "Socket",
    "query": "label_values(php_fpm_accepted_connections_total, socket_path)"
   }
  ]
 },
 "panels": [
  { "title": "PHP FPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PHP-FPM Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "php_fpm_up{instance=~\"^$Host$\", socket_path=~\"$Socket$\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time()-(php_fpm_start_time_seconds{instance=~\"^$Host$\", socket_path=~\"$Socket$\"})",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Workers  Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "( php_fpm_active_processes{instance=~\"^$Host$\", socket_path=~\"$Socket$\"} / php_fpm_max_active_processes{instance=~\"^$Host$\", socket_path=~\"$Socket$\"} )"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Accepted Connections Rate",
   "type": "graph",
   "description": "Total number of accepted connections",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(php_fpm_accepted_connections_total{instance=~\"^$Host$\", socket_path=~\"$Socket$\"}[$Interval])",
     "legendFormat": "Accepted Connections Rate"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "php_fpm_max_active_processes{instance=~\"^$Host$\", socket_path=~\"$Socket$\"}",
     "legendFormat": "Max Active"
    },
    {
     "expr": "php_fpm_active_processes{instance=~\"^$Host$\", socket_path=~\"$Socket$\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "php_fpm_idle_processes{instance=~\"^$Host$\", socket_path=~\"$Socket$\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Slow Requests Rate",
   "type": "graph",
   "description": "Number of requests that exceed request_slowlog_timeout",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(php_fpm_slow_requests{instance=~\"^$Host$\", socket_path=~\"$Socket$\"}[$Interval])",
     "legendFormat": "Slow Requests Rate "
    }
   ]
  },
  {
   "title": "Listen Queue Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "php_fpm_listen_queue{instance=~\"^$Host$\"}",
     "legendFormat": "Queue"
    },
    {
     "expr": "php_fpm_listen_queue_length{instance=~\"^$Host$\", socket_path=~\"$Socket$\"}",
     "legendFormat": "Queue Length"
    }
   ]
  }
 ]
}