{
 "title": "PHP-FPM - Multiple pools",
 "description": "PHP-FPM aggregated data for multiple pools.",
 "tags": [ "php-fpm" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "label_values(php_fpm_accepted_connections_total, instance)"
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "Interval", "label": "Time Interval", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "Pool",
    "label": "Pool",
    "query": "label_values(php_fpm_accepted_connections_total, socket_path)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(php_fpm_up{instance=~\"^$Host$\", socket_path=~\"$Pool$\"})",
     "legendFormat": "{{socket_path}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time()-(php_fpm_start_time_seconds{instance=~\"^$Host$\", socket_path=~\"$Pool\"})",
     "legendFormat": "{{socket_path}}"
    }
   ]
  },
  {
   "title": "Pool Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (socket_path) (php_fpm_active_processes{instance=~\"^$Host$\"}) / sum by (socket_path) ( php_fpm_max_active_processes{instance=~\"^$Host$\"})",
     "legendFormat": "{{ socket_path }}"
    }
   ]
  },
  { "title": "PHP FPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Accepted Connections Rate",
   "type": "graph",
   "description": "Total number of accepted connections",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (socket_path) (rate(php_fpm_accepted_connections_total{instance=~\"^$Host$\"} [$Interval]))",
     "legendFormat": "{{socket_path}}"
    }
   ]
  },
  {
   "title": "Slow Requests Rate",
   "type": "graph",
   "description": "Number of requests that exceed request_slowlog_timeout",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (socket_path) (rate(php_fpm_slow_requests{instance=~\"^$Host$\"} [$Interval]))",
     "legendFormat": "{{ socket_path }} "
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active processes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(php_fpm_active_processes{instance=~\"^$Host$\"}) by (socket_path )",
     "legendFormat": "{{ socket_path }} "
    }
   ]
  },
  {
   "title": "Idle processes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (socket_path) (php_fpm_idle_processes{instance=~\"^$Host$\"})",
     "legendFormat": "{{ socket_path }} "
    }
   ]
  },
  {
   "title": "Max children reached",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (socket_path) (php_fpm_max_children_reached{instance=~\"^$Host$\"} )",
     "legendFormat": "{{ socket_path }} "
    }
   ]
  },
  {
   "title": "Max active processes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (socket_path) (php_fpm_max_active_processes{instance=~\"^$Host$\"})",
     "legendFormat": "{{ socket_path }} "
    }
   ]
  },
  {
   "title": "Listen Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (socket_path) (rate(php_fpm_listen_queue{instance=~\"^$Host$\"} [$Interval]))",
     "legendFormat": "{{socket_path }} "
    }
   ]
  },
  {
   "title": "Listen Queue Lengtht",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (socket_path) (rate(php_fpm_listen_queue_length{instance=~\"^$Host$\"} [$Interval]))",
     "legendFormat": "{{socket_path }}"
    }
   ]
  }
 ]
}