---

version: '3.4'

x-logging:
  &default-logging
  driver: 'json-file'
  options:
    max-size: "${LOGGING_MAX_SIZE}"
    max-file: "${LOGGING_MAX_FILE}"

networks:
  monitoring_core: {}
  prometheus_servers: {}
  services:
    external:
      name: 'services'

volumes:
  alertmanager_data: {}
  chronograf_data: {}
  grafana_data: {}
  influxdb_data: {}
  postgres_data: {}
  prometheus_core_data: {}
  prometheus_databases_data: {}
  prometheus_nodes_data: {}
  prometheus_services_data: {}


services:
  alertmanager:
    image: "${ALERT_MANAGER_IMAGE_NAME}:${ALERT_MANAGER_IMAGE_VERSION}"
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://127.0.0.1:9093'
    restart: 'unless-stopped'
    logging: *default-logging
    expose:
      - 9093
    volumes:
      - 'alertmanager_data:/alertmanager'
      - './config/alertmanager/config.yml:/etc/alertmanager/config.yml:ro'
      - '/etc/ssl/certs:/etc/ssl/certs:ro'
      - '/etc/pki:/etc/pki:ro'
    networks:
      - 'monitoring_core'
      - 'services'

  blackbox_exporter:
    image: "${BLACKBOX_EXPORTER_IMAGE_NAME}:${BLACKBOX_EXPORTER_IMAGE_VERSION}"
    restart: 'unless-stopped'
    logging: *default-logging
    expose:
      - 9115
    networks:
      - 'monitoring_core'
      - 'services'
    volumes:
      - './config/blackbox_exporter/config.yml:/etc/blackbox_exporter/config.yml:ro'

  chronograf:
    image: "${CHRONOGRAF_IMAGE_NAME}:${CHRONOGRAF_IMAGE_VERSION}"
    command:
      - '--influxdb-url=http://influxdb:8086'
    restart: 'unless-stopped'
    logging: *default-logging
    expose:
      - 8888
    networks:
      - 'monitoring_core'
      - 'services'
    volumes:
      - 'chronograf_data:/var/lib/chronograf'

  postgres:
    image: "${POSTGRES_IMAGE_NAME}:${POSTGRES_IMAGE_VERSION}"
    restart: 'unless-stopped'
    logging: *default-logging
    env_file:
      - './env/postgres.env'
    networks:
      - 'monitoring_core'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  grafana:
    image: "${GRAFANA_IMAGE_NAME}:${GRAFANA_IMAGE_VERSION}"
    restart: 'unless-stopped'
    logging: *default-logging
    volumes:
      - 'grafana_data:/var/lib/grafana'
      - './config/grafana/ldap/ldap.toml:/etc/grafana/ldap.toml'
      - './config/grafana/provisionning/datasources:/etc/grafana/provisioning/datasources'
      - './config/grafana/provisionning/dashboards:/etc/grafana/provisioning/dashboards'
      - './config/grafana/dashboards:/var/lib/grafana/dashboards'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MongoDB_ClusterSummary.json:/var/lib/grafana/dashboards/databases/MongoDB_Cluster_Summary.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MongoDB_InMemory.json:/var/lib/grafana/dashboards/databases/MongoDB_InMemory.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MongoDB_MMAPv1.json:/var/lib/grafana/dashboards/databases/MongoDB_MMAPv1.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MongoDB_Overview.json:/var/lib/grafana/dashboards/databases/MongoDB_Overview.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MongoDB_ReplSet.json:/var/lib/grafana/dashboards/databases/MongoDB_ReplSet.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MongoDB_RocksDB.json:/var/lib/grafana/dashboards/databases/MongoDB_RocksDB.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MongoDB_WiredTiger.json:/var/lib/grafana/dashboards/databases/MongoDB_WiredTiger.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/Summary_Dashboard.json:/var/lib/grafana/dashboards/databases/Summary_Dashboard.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MySQL_Command_Handler_Counters_Compare.json:/var/lib/grafana/dashboards/databases/MySQL_Command_Handler_Counters_Compare.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MySQL_InnoDB_Compression.json:/var/lib/grafana/dashboards/databases/MySQL_InnoDB_Compression.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MySQL_InnoDB_Metrics_Advanced.json:/var/lib/grafana/dashboards/databases/MySQL_InnoDB_Metrics_Advanced.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MySQL_InnoDB_Metrics.json:/var/lib/grafana/dashboards/databases/MySQL_InnoDB_Metrics.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MySQL_MyISAM_Aria_Metrics.json:/var/lib/grafana/dashboards/databases/MySQL_MyISAM_Aria_Metrics.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MySQL_MyRocks_Metrics.json:/var/lib/grafana/dashboards/databases/MySQL_MyRocks_Metrics.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MySQL_Overview.json:/var/lib/grafana/dashboards/databases/MySQL_Overview.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MySQL_Performance_Schema.json:/var/lib/grafana/dashboards/databases/MySQL_Performance_Schema.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MySQL_Performance_Schema_Wait_Event_Analyses.json:/var/lib/grafana/dashboards/databases/MySQL_Performance_Schema_Wait_Event_Analyses.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MySQL_Query_Response_Time.json:/var/lib/grafana/dashboards/databases/MySQL_Query_Response_Time.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MySQL_Replication.json:/var/lib/grafana/dashboards/databases/MySQL_Replication.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MySQL_Table_Statistics.json:/var/lib/grafana/dashboards/databases/MySQL_Table_Statistics.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MySQL_TokuDB_Metrics.json:/var/lib/grafana/dashboards/databases/MySQL_TokuDB_Metrics.json'
      - './vendor/github.com/percona/grafana-dashboards/dashboards/MySQL_User_Statistics.json:/var/lib/grafana/dashboards/databases/MySQL_User_Statistics.json'
    env_file:
      - './env/grafana.env'
    expose:
      - 3000
    networks:
      - 'monitoring_core'
      - 'services'

  influxdb:
    image: "${INFLUXDB_IMAGE_NAME}:${INFLUXDB_IMAGE_VERSION}"
    command:
      - 'influxd'
      - '-config'
      - '/etc/influxdb/influxdb.conf'
    restart: 'unless-stopped'
    logging: *default-logging
    env_file:
      - 'env/influxdb.env'
    expose:
      - 4242
      - 8086
    networks:
      - 'monitoring_core'
    volumes:
      - 'influxdb_data:/var/lib/influxdb'
      - './config/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf'

  influxdb_exporter:
    image: "${INFLUXDB_EXPORTER_IMAGE_NAME}:${INFLUXDB_EXPORTER_IMAGE_VERSION}"
    command:
      - '--influx.url=http://influxdb:8086'
    restart: 'unless-stopped'
    logging: *default-logging
    expose:
      - 9424
    networks:
      - 'monitoring_core'

  prometheus_core:
    image: "${PROMETHEUS_IMAGE_NAME}:${PROMETHEUS_IMAGE_VERSION}"
    command:
      - '--config.file=/etc/prometheus/prometheus-core.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1h'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.external-url=http://127.0.0.1:9090'
    restart: 'unless-stopped'
    logging: *default-logging
    expose:
      - 9090
    networks:
      monitoring_core:
        aliases:
          - 'monitoring_core.prometheus'
      prometheus_servers:
        aliases:
          - 'prometheus_servers.core'
      services:
        aliases:
          - 'services.prometheus'
    volumes:
      - './config/prometheus/:/etc/prometheus/'
      - 'prometheus_core_data:/prometheus/'

  prometheus_databases:
    image: "${PROMETHEUS_IMAGE_NAME}:${PROMETHEUS_IMAGE_VERSION}"
    command:
      - '--config.file=/etc/prometheus/prometheus-databases.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1h'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.external-url=http://0.0.0.0:9090'
    restart: 'unless-stopped'
    logging: *default-logging
    expose:
      - 9090
    networks:
      monitoring_core:
        aliases:
          - 'prometheus_servers.databases'
      prometheus_servers:
        aliases:
          - 'prometheus_servers.databases'
    volumes:
      - './config/prometheus/:/etc/prometheus/'
      - 'prometheus_databases_data:/prometheus/'

  prometheus_nodes:
    image: "${PROMETHEUS_IMAGE_NAME}:${PROMETHEUS_IMAGE_VERSION}"
    command:
      - '--config.file=/etc/prometheus/prometheus-nodes.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1h'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.external-url=http://0.0.0.0:9090'
    restart: 'unless-stopped'
    logging: *default-logging
    expose:
      - 9090
    networks:
      monitoring_core:
        aliases:
          - 'prometheus_servers.nodes'
      prometheus_servers:
        aliases:
          - 'prometheus_servers.nodes'
    volumes:
      - './config/prometheus/:/etc/prometheus/'
      - 'prometheus_nodes_data:/prometheus/'

  prometheus_services:
    image: "${PROMETHEUS_IMAGE_NAME}:${PROMETHEUS_IMAGE_VERSION}"
    command:
      - '--config.file=/etc/prometheus/prometheus-services.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1h'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: 'unless-stopped'
    logging: *default-logging
    expose:
      - 9090
    networks:
      monitoring_core:
        aliases:
          - 'prometheus_servers.services'
      prometheus_servers:
        aliases:
          - 'prometheus_servers.services'
    volumes:
      - './config/prometheus/:/etc/prometheus/'
      - 'prometheus_services_data:/prometheus/'

  push_gateway:
    image: "${PUSH_GATEWAY_IMAGE_NAME}:${PUSH_GATEWAY_IMAGE_VERSION}"
    restart: 'unless-stopped'
    logging: *default-logging
    expose:
      - 9091
    ports:
      - "${LISTEN_IP_ADDRESS}:9091:9091"
    networks:
      - 'monitoring_core'
      - 'services'
