{
 "title": "Elasticsearch",
 "description": "ElasticSearch metrics from prometheus exporter",
 "tags": [ "elasticsearch" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "15s,30s,1m,5m,1h,6h,1d" },
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(elasticsearch_process_cpu_percent{node_type=~\"$node_type\"},node)"
   },
   { "name": "node_type", "label": "Node type", "query": "label_values(node_type)" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_pending_tasks{cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "active primary shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "repeat": "shard_type",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_active_primary_shards{cluster=\"$cluster\", node_type=~\"$node_type\"})"
    }
   ]
  },
  {
   "title": "active shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_active_shards{cluster=\"$cluster\", node_type=~\"$node_type\"})"
    }
   ]
  },
  {
   "title": "initializing shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_initializing_shards{cluster=\"$cluster\", node_type=~\"$node_type\"})"
    }
   ]
  },
  {
   "title": "relocating shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_relocating_shards{cluster=\"$cluster\", node_type=~\"$node_type\"})"
    }
   ]
  },
  {
   "title": "relocating shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_delayed_unassigned_shards{cluster=\"$cluster\", node_type=~\"$node_type\"})"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "1-(elasticsearch_filesystem_data_available_bytes{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}/elasticsearch_filesystem_data_size_bytes{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"})",
     "legendFormat": "{{node}} - {{path}}"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Documents count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Documents" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Documents indexed rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Documents deleted rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_delete_total{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Documents merged rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_total{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Query time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Merging time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Field data memory size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_fielddata_memory_size_bytes{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Field data evictions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_fielddata_evictions{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Query cache size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_query_cache_memory_size_bytes{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Query cache evictions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_query_cache_evictions{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Heap used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes", "label": "Heap" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{area=\"heap\", cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}",
     "legendFormat": "{{node}} - heap used"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "GCs" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}[$interval])",
     "legendFormat": "{{node}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=\"$cluster\",node=~\"$node\", node_type=~\"$node_type\"}[$interval])",
     "legendFormat": "{{node}} - {{gc}}"
    }
   ]
  }
 ]
}