{
 "title": "Logstash",
 "description": "Logstash monitoring via prometheus",
 "tags": [
  "elasticsearch",
  "logstash"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "15s,30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "PIPELINE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(logstash_node_pipeline_duration_seconds_total[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Events in rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logstash_node_pipeline_events_in_total[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Events filtered rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logstash_node_pipeline_events_filtered_total[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Events out rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logstash_node_pipeline_events_out_total[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "PLUGINS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Duration rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_duration_seconds_total[$interval])) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Failures rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_failures_total[$interval])) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Events In rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_events_in_total[$interval])) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Events Out rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logstash_node_plugin_events_out_total[$interval])) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Heap used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes", "label": "Heap" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "logstash_node_mem_heap_used_bytes",
     "legendFormat": "{{instance}} - heap used"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "logstash_node_process_open_filedescriptors",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "GCs" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "rate(logstash_node_gc_collection_total[$interval])",
     "legendFormat": "{{instance}} - {{collector}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "s", "label": "GCs" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "rate(logstash_node_gc_collection_duration_seconds_total[$interval])",
     "legendFormat": "{{instance}} - {{collector}}"
    }
   ]
  }
 ]
}