{
 "title": "Elasticsearch - Additional metrics (to merge)",
 "description": "Graphs for all elasticsearch_exporter metrics",
 "tags": [ "elasticsearch" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(elasticsearch_indices_docs{job=\"elasticsearch\"}, cluster)"
   },
   {
    "name": "host",
    "query": "label_values(elasticsearch_indices_docs{job=\"elasticsearch\",cluster=\"$cluster\"}, host)"
   },
   {
    "name": "node",
    "query": "label_values(elasticsearch_filesystem_data_size_bytes{job=\"elasticsearch\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "exporter  -  scrapes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_cluster_health_total_scrapes{job=\"elasticsearch\"}[5m])",
     "legendFormat": "cluster_health - {{instance}}"
    },
    {
     "expr": "irate(elasticsearch_node_stats_total_scrapes{job=\"elasticsearch\"}[5m])",
     "legendFormat": "node_stats - {{instance}}"
    }
   ]
  },
  {
   "title": "exporter  -  json_parse_failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_json_parse_failures{job=\"elasticsearch\"}",
     "legendFormat": "cluster_health - {{instance}}"
    },
    {
     "expr": "elasticsearch_node_stats_json_parse_failures{job=\"elasticsearch\"}",
     "legendFormat": "node_stats - {{instance}}"
    }
   ]
  },
  {
   "title": "exporter - up",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_up{job=\"elasticsearch\"}",
     "legendFormat": "cluster_health - {{instance}}"
    },
    {
     "expr": "elasticsearch_node_stats_up{job=\"elasticsearch\"}",
     "legendFormat": "node_stats - {{instance}}"
    }
   ]
  },
  {
   "title": "cluster: $cluster  -  shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{job=\"elasticsearch\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  active_primary"
    },
    {
     "expr": "elasticsearch_cluster_health_active_shards{job=\"elasticsearch\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  active (total)"
    },
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{job=\"elasticsearch\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  delayed_unassigned"
    },
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{job=\"elasticsearch\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  initializing"
    },
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{job=\"elasticsearch\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  relocating"
    },
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{job=\"elasticsearch\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  unassigned"
    }
   ]
  },
  {
   "title": "cluster: $cluster  -  number_of_nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{job=\"elasticsearch\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  data_nodes"
    },
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{job=\"elasticsearch\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  nodes (total)"
    }
   ]
  },
  {
   "title": "cluster: $cluster  -  health_number_of",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_in_flight_fetch{job=\"elasticsearch\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  in_flight_fetch"
    },
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{job=\"elasticsearch\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  pending_tasks"
    },
    {
     "expr": "elasticsearch_cluster_health_timed_out{job=\"elasticsearch\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  timed_out"
    }
   ]
  },
  {
   "title": "cluster: $cluster  -  health_status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{job=\"elasticsearch\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}  -  {{color}}"
    }
   ]
  },
  {
   "title": "breakers_estimated_size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_breakers_estimated_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "{{breaker}}"
    }
   ]
  },
  {
   "title": "breakers_limit_size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_breakers_limit_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "{{breaker}}"
    }
   ]
  },
  {
   "title": "breakers_tripped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_breakers_tripped{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "{{breaker}}"
    }
   ]
  },
  {
   "title": "filesystem_data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_filesystem_data_available_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "available"
    },
    {
     "expr": "elasticsearch_filesystem_data_free_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "free"
    },
    {
     "expr": "elasticsearch_filesystem_data_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "indices_docs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "total"
    },
    {
     "expr": "elasticsearch_indices_docs_deleted{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "deleted"
    }
   ]
  },
  {
   "title": "evictions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_fielddata_evictions{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "fielddata"
    },
    {
     "expr": "elasticsearch_indices_filter_cache_evictions{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "filter_cache"
    },
    {
     "expr": "elasticsearch_indices_query_cache_evictions{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "query_cache"
    },
    {
     "expr": "elasticsearch_indices_request_cache_evictions{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "request_cache"
    }
   ]
  },
  {
   "title": "memory_size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_fielddata_memory_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "fielddata"
    },
    {
     "expr": "elasticsearch_indices_filter_cache_memory_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "filter_cache"
    },
    {
     "expr": "elasticsearch_indices_query_cache_memory_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "query_cache"
    },
    {
     "expr": "elasticsearch_indices_request_cache_memory_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "request_cache"
    },
    {
     "expr": "elasticsearch_indices_segments_memory_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "segments"
    },
    {
     "expr": "elasticsearch_indices_translog_size_in_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "translog"
    }
   ]
  },
  {
   "title": "operations - time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_flush_time_seconds{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "flush_time"
    },
    {
     "expr": "irate(elasticsearch_indices_get_exists_time_seconds{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "get_exists"
    },
    {
     "expr": "irate(elasticsearch_indices_get_missing_time_seconds{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "get_missing"
    },
    {
     "expr": "irate(elasticsearch_indices_get_time_seconds{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "get (total)"
    },
    {
     "expr": "irate(elasticsearch_indices_indexing_delete_time_seconds_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "indexing_delete"
    },
    {
     "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "indexing_index"
    },
    {
     "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "merges"
    },
    {
     "expr": "irate(elasticsearch_indices_refresh_time_seconds_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "refresh"
    },
    {
     "expr": "irate(elasticsearch_indices_search_fetch_time_seconds{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "search_fetch"
    },
    {
     "expr": "irate(elasticsearch_indices_search_query_time_seconds{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "search_query"
    },
    {
     "expr": "irate(elasticsearch_indices_store_throttle_time_seconds_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "store_throttle"
    }
   ]
  },
  {
   "title": "operations - count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_flush_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "flush_total"
    },
    {
     "expr": "irate(elasticsearch_indices_get_exists_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "get_exists"
    },
    {
     "expr": "irate(elasticsearch_indices_get_missing_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "get_missing"
    },
    {
     "expr": "irate(elasticsearch_indices_get_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "get (total)"
    },
    {
     "expr": "irate(elasticsearch_indices_indexing_delete_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "indexing_delete"
    },
    {
     "expr": "irate(elasticsearch_indices_indexing_index_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "indexing_index"
    },
    {
     "expr": "irate(elasticsearch_indices_merges_docs_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "merges_docs"
    },
    {
     "expr": "irate(elasticsearch_indices_merges_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "merges"
    },
    {
     "expr": "irate(elasticsearch_indices_refresh_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "refresh"
    },
    {
     "expr": "irate(elasticsearch_indices_search_fetch_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "search_fetch"
    },
    {
     "expr": "irate(elasticsearch_indices_search_query_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "search_query"
    },
    {
     "expr": "irate(elasticsearch_indices_translog_operations{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "translog"
    }
   ]
  },
  {
   "title": "merges_total_size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_merges_total_size_bytes_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "merges_total_size"
    }
   ]
  },
  {
   "title": "segments_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_count{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "segments_count"
    }
   ]
  },
  {
   "title": "indices_store_size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_store_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "indices_store_size"
    }
   ]
  },
  {
   "title": "jvm_gc_collection - count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_count{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "jvm_gc_collection - duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "jvm_memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_committed_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "committed - {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "max - {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "used - {{area}}"
    }
   ]
  },
  {
   "title": "process_cpu_percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "process_cpu_time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_process_cpu_time_seconds_sum{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "process_mem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_mem_resident_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "elasticsearch_process_mem_share_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "share"
    },
    {
     "expr": "elasticsearch_process_mem_virtual_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "process_open_files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_open_files_count{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "open_files"
    }
   ]
  },
  {
   "title": "thread_pool_active",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_active_count{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "thread_pool_completed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 194 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_thread_pool_completed_count{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "thread_pool_queue",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 204 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_queue_count{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "thread_pool_rejected",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 214 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_thread_pool_rejected_count{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "thread_pool_threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_threads_count{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "transport packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 231 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_transport_rx_packets_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "rx"
    },
    {
     "expr": "irate(elasticsearch_transport_tx_packets_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "transport size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 238 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_transport_rx_size_bytes_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "rx"
    },
    {
     "expr": "irate(elasticsearch_transport_tx_size_bytes_total{job=\"elasticsearch\",cluster=~\"$cluster\",host=~\"$host\"}[5m])",
     "legendFormat": "tx"
    }
   ]
  }
 ]
}