---

global:
  scrape_interval: '10s'
  evaluation_interval: '10s'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

remote_read:
  - url: "http://influxdb:8086/api/v1/prom/read?db=prometheus"

remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db=prometheus"

rule_files:
  - '/etc/prometheus/rules/common/*'
  - '/etc/prometheus/rules/customer/*'

scrape_configs:
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']

  - job_name: 'influxdb_exporter'
    static_configs:
      - targets: ['influxdb_exporter:9424']
