---

global:
  scrape_interval: '10s'
  evaluation_interval: '10s'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

remote_read:
  - url: "http://influxdb:8086/api/v1/prom/read?db=prometheus"

remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db=prometheus"

rule_files:
  - '/etc/prometheus/rules/common/*'
  - '/etc/prometheus/rules/customer/*'

scrape_configs:
  - job_name: 'blackbox'
    metrics_path: '/probe'
    params:
      module:
        - 'http_2xx'
    static_configs:
      - targets:
          - 'github.com'
          - 'about.gitlab.com'
    relabel_configs:
      - source_labels: ['__address__']
        target_label: '__param_target'
      - source_labels: ['__param_target']
        target_label: 'instance'
      - target_label: '__address__'
        replacement: 'blackbox_exporter:9115'

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'nginx_exporter'
    dns_sd_configs:
      - names:
        - '_nginx-exporter._tcp.test.fr.internal.infopen.net'

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus_servers.core:9090'
          - 'prometheus_servers.databases:9090'
          - 'prometheus_servers.nodes:9090'
          - 'prometheus_servers.services:9090'

  - job_name: 'push_gateway'
    honor_labels: true
    static_configs:
      - targets: ['push_gateway:9091']
